---
title: "Spatial Statistics Final Project"
author: "Brusco, Bianca; Wang, Hongting; Yang, Lingfeng"
date: "9/28/2018"
output: pdf_document
---

    ```{r setup, include = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE)
    library(ggplot2)
    library(lattice)
    library(spdep)
    library(RColorBrewer)
    library(classInt)
    library(rgdal)
    library(formatR)
    library(sm)
    library(tidyverse)
    library(revgeo)
    library(ggmap)
    library(sp)
    
    #snippet to override r-chunk fonts.
    def.chunk.hook  <- knitr::knit_hooks$get("chunk")
    knitr::knit_hooks$set(chunk = function(x, options) {
       x <- def.chunk.hook(x, options)
       ifelse(options$size != "normalsize", paste0("\\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
    })
    ```

# Importing and Cleaning data
## Importing data
(1). NYC Stop & Frisk data
(2). Housing value panel data
```{r init-1,size="tiny",warning=FALSE,message=FALSE}
# Housing value
hvraw <- read.csv("data/Trimmed_home_value.csv", header = T)

# Stop & Frisk
load("data/sqf.RData")
#stops2013 <- subset(stops,year==2013)
#stops2013[1:3,c("date","precinct","suspected.crime","suspect.race","found.weapon")]
```

## Cleaning data
### Housing Value
```{r}
# select relevant date range for housing value, filter out other cities
hv <- hvraw %>% filter(City == "New York") %>% select(RegionName, CountyName, X2005.12:X2014.01) %>% arrange(RegionName)
```

### Stop & Frisk
```{r}
# filter out NAs for lon and lat, 1303 NAs and 47 "1900-12-31" for date, then select columns of interest, sorted in chronological order
sf <- stops %>% filter(lat > 40.2 & !is.na(lat)) %>% filter(date >= "2006-01-01" & date <= "2013-12-31") %>% select(year, date, time, precinct, suspected.crime, frisked, suspect.race, found.weapon, lat, lon) %>% arrange(date, time)


```


```{r}
# zip code shape file
zipraw <- readOGR("data/zip_code/ZIP_CODE_040114.shp")
nyc <- readOGR("data/Borough_Boundaries/geo_export_5e515234-1937-40b5-b942-1ef10ea3ea45.shp")

# change projection method to lon/lat
zipbd <-  spTransform(zipraw, CRS("+proj=longlat +ellps=WGS84 +no_defs"))

# test
plot(zipbd)
points(sf$lon[1:10000], sf$lat[1:10000], pch = ".", cex = 2, col = sf[1:10000, ]$suspect.race)
```

```{r}
# Convert lon/lat into zip code, 300/min -> 18,000/hr -> 432,000/day, 9.15 day LOL
#Sys.time()
#x <- rep(0, 20)
#for (i in 1:20) {
#  x[i] <- as.numeric(revgeo(sf$lon[i], sf$lat[i], output = "hash", item = "zip"))
#}
#Sys.time()

# experimenting with reversing geo code
# update: IT WORKS! 500,000/14s -> takes around 110s to run the whole thing
#Sys.time()
#coord1 <- cbind(sf$lon[1:500000], sf$lat[1:500000])
#points <- SpatialPoints(coord1, CRS("+proj=longlat +ellps=WGS84 +no_defs"))
#y <- over(points, zipbd)
#summary(y)
#Sys.time()
#

coord1 <- cbind(sf$lon, sf$lat)
points <- SpatialPoints(coord1, CRS("+proj=longlat +ellps=WGS84 +no_defs"))
reversezip <- over(points, zipbd)


```

```{r}
plot(zipbd, col = "green")
points(sf$lon[which(is.na(reversezip$ZIPCODE))], sf$lat[which(is.na(reversezip$ZIPCODE))], pch = ".", cex = 4, col = "red")
```

